// <auto-generated />
using System;
using CaseTrackingAPI.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseTrackingAPI.Migrations
{
    [DbContext(typeof(CaseDbContext))]
    partial class CaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseTrackingAPI.Models.BiologicalTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("BiologicalTraces");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("DCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DCaseId");

                    b.ToTable("Files");

                    b.HasDiscriminator().HasValue("DFile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("DCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DCaseId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RetrievalTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Evidences");

                    b.HasDiscriminator().HasValue("Evidence");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MentalState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateGiven")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.PDF", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.DFile");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("PDF");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.PNG", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.DFile");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("PNG");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.BiologicalEvidence", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.Evidence");

                    b.Property<string>("RetrievalTechnique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BiologicalEvidence");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.PhysicalEvidence", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.Evidence");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContainsBiologicalTraces")
                        .HasColumnType("bit");

                    b.Property<string>("DangerLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresExamination")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedInCrime")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("PhysicalEvidence");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Suspect", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.Person");

                    b.Property<int?>("DCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Suspicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DCaseId");

                    b.HasDiscriminator().HasValue("Suspect");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Victim", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.Person");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasIndex("DCaseId");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("DCaseId")
                                .HasColumnName("Victim_DCaseId");
                        });

                    b.HasDiscriminator().HasValue("Victim");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Witness", b =>
                {
                    b.HasBaseType("CaseTrackingAPI.Models.Person");

                    b.Property<int?>("DCaseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuspected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderObservation")
                        .HasColumnType("bit");

                    b.Property<string>("RelationToVictim")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("DCaseId");

                    b.ToTable("Persons", t =>
                        {
                            t.Property("DCaseId")
                                .HasColumnName("Witness_DCaseId");
                        });

                    b.HasDiscriminator().HasValue("Witness");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.BiologicalTrace", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.Person", "Person")
                        .WithMany("BiologicalTraces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DFile", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.DCase", null)
                        .WithMany("Files")
                        .HasForeignKey("DCaseId");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DTask", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.DCase", null)
                        .WithMany("CaseTasks")
                        .HasForeignKey("DCaseId");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Evidence", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.Person", "Person")
                        .WithMany("Evidences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Statement", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.Person", "Person")
                        .WithMany("Statements")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Suspect", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.DCase", null)
                        .WithMany("Suspects")
                        .HasForeignKey("DCaseId");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Victim", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.DCase", null)
                        .WithMany("Victims")
                        .HasForeignKey("DCaseId");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Witness", b =>
                {
                    b.HasOne("CaseTrackingAPI.Models.DCase", null)
                        .WithMany("Witnesses")
                        .HasForeignKey("DCaseId");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.DCase", b =>
                {
                    b.Navigation("CaseTasks");

                    b.Navigation("Files");

                    b.Navigation("Suspects");

                    b.Navigation("Victims");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("CaseTrackingAPI.Models.Person", b =>
                {
                    b.Navigation("BiologicalTraces");

                    b.Navigation("Evidences");

                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
